
project_id = "ryujklxvochfkuokgduz"

[functions.vector-store]
verify_jwt = true

[functions.agent-orchestrator]
verify_jwt = true

[functions.chat-with-agent]
verify_jwt = true

[functions.process-document]
verify_jwt = true

[functions.model-provider]
verify_jwt = true

[functions.document-embeddings]
verify_jwt = true
