
project_id = "ryujklxvochfkuokgduz"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[realtime]
enabled = true

[studio]
enabled = true
port = 54323

[functions.model-provider]
verify_jwt = true
